GET  http://localhost:5000/users

###
GET  http://localhost:5000/users/12

#####
POST  http://localhost:5000/users
Content-Type: application/json

{
    "name":"John Doe",
    "email":"john@gmail.com",
    "gender":"Male"
}

######

PATCH   http://localhost:5000/users/12
Content-Type: application/json

{
    "name":"Jo Doe",
    "email":"jo@gmail.com",
    "gender":"FEMALE"
}


####
DELETE  http://localhost:5000/users/12


